### ISSUE TITLE
R-T3.4-18: AnsibleMetrics should allow developers to understand when a metric's value is problematic

### ISSUE THREAD

**Issue by dardin88** [radon-h2020/radon-ansible-metrics-plugin#2]
ID | R-T3.4-18
-- | --
Section | WP3: Methodology and Quality Assurance Requirements
Type | FUNCTIONAL_SUITABILITY
User Story | Currently, AnsibleMetrics reports the values of the mined metrics. However, it does not provide any additional feedback. The developer cannot understand if the values are too high or too low. Therefore, the information is not actionable.
Requirement | Based on all projects mined by IaC miner, AnsibleMetric should help developers understand which metrics are problematic by showing if they are outliers in the metric distribution. In other words, it should provide visual feedback concerning the severity of the metrics.
Priority | Should have
Affected Tools | DEFECT_PRED_TOOL
Means of Verification | Direct implementation on IDE, feature checklist, case-study

**Comment by dardin88** [comment]
@gcasale

**Comment by gcasale** [comment]
Approved
